### PR TITLE
Allow setting Property when creating AttAttribute

### PR DESCRIPTION
**Pull request by bjornharrtell**
I have a use case where part of my model attributes are not static, so I need a way to create AttAttribute in runtime. To properly do that I need to be able to tie a AttrAttribute to a PropertyInfo which this PR adds as an alternative constructor.

### CODE REVIEW

**Comment by bjornharrtell** [comment]
Alternatively could make the setter for Property non-internal?

**Comment by maurei** [comment]
Hi Bjorn, thanks for your efforts. Would you mind elaborating on your use-case with an example? Preferably if you'd open up an issue for type of background information so we can discuss it further there

**Comment by bjornharrtell** [comment]
@maurei that's reasonable, I've made an attempt in #814.

**Comment by bjornharrtell** [comment]
See https://github.com/json-api-dotnet/JsonApiDotNetCore/issues/814 for the discussion which led this to be closed.

**Pull request closed without merging**
