### PR TITLE
Add Negative filter

### PR DESCRIPTION
**Pull request by milosloub**
Only extension of current filter system by adding NotEqual case for filter[attribute]=ne:value

### CODE REVIEW

**Comment by jaredcnance** [comment]
Awesome! Thanks! Would you mind adding tests? You should be able to just add it onto these: https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/master/test/JsonApiDotNetCoreExampleTests/Acceptance/Spec/AttributeFilterTests.cs

**Comment by milosloub** [comment]
Sure, I'll have some problems with testing. Locally tests passes, but after push test fail. I'll investigate this later

**Comment by milosloub** [comment]
Test is fixed now. Problem was my clear postgres db in docker container. While running this test, I didn't count with data from previous tests. 

Btw I have another idea of extending filter for array use-cases. For example I'm
looking to find those people whose age's are present in the arrayValues. 
So "filter[age]=in:[15,18,30]" would be translated as:
People.Where(s=>arrayValues.Contains(s.age))
What do you think about this solution?

**Comment by jaredcnance** [comment]
@milosloub that sounds good.

**Pull request merged**
