### PR TITLE
Fix broken doc links

### PR DESCRIPTION
**Pull request by leandroaraujosouza**
This PR fixes broken links in the [docs/usage/extensibility/resource-definitions.md](https://github.com/json-api-dotnet/JsonApiDotNetCore/pull/1171/files#diff-fcf48abaccb657a94fde70e3b54f31c30faeb9f9608ac5dfb85927286fa8a3a8) file

Closes #{ISSUE_NUMBER}

#### QUALITY CHECKLIST
- [ ] Changes implemented in code
- [X] Complies with our [contributing guidelines](https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/master/.github/CONTRIBUTING.md)
- [ ] Adapted tests
- [X] Documentation updated

### CODE REVIEW

**Comment by bkoelman** [comment]
Hi @leandroaraujosouza, thanks for taking the time to create a PR. Though I'm confused: where do you see these links are broken? They seem to render properly at https://www.jsonapi.net/usage/extensibility/resource-definitions.html. The `~` paths are resolved by docfx, which we use to build the documentation website. We use these links so that docfx validates them and reports build warnings when they break.

**Comment by leandroaraujosouza** [comment]
> Hi @leandroaraujosouza, thanks for taking the time to create a PR. Though I'm confused: where do you see these links are broken? They seem to render properly at https://www.jsonapi.net/usage/extensibility/resource-definitions.html. The `~` paths are resolved by docfx, which we use to build the documentation website. We use these links so that docfx validates them and reports build warnings when they break.

Hi @bkoelman I see them broken when browsing through the repo -> https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/master/docs/usage/extensibility/resource-definitions.md

image

I'll be reading more about docfx to understand better so I can propose a solution that works in both cases.

**Comment by bkoelman** [comment]
Hi @leandroaraujosouza, are you still working on this?

**Comment by bkoelman** [comment]
Closing due to inactivity.

**Pull request closed without merging**
