### PR TITLE
[draft] Feat/serializer context decoupling

### PR DESCRIPTION
**Pull request by wisepotato**
The main goal of this PR is to counteract the coupling observed in JADNC. Let's make it more testable!

- [x] No more `JsonApiContext` dependency in Controllers
- [x] The entity is set via `ResourceGraph` in the middleware now
- [x] no more `ApplyContext<T>` in the controller, making for a coupling that is not needed
- [x] get all tests working

#### BUG FIX
- [x] reproduce issue in tests
- [ ] fix issue
- [ ] bump package version

#### FEATURE
- [ ] write tests that address the requirements outlined in the issue
- [ ] fulfill the feature requirements
- [ ] bump package version

### CODE REVIEW

**Comment by wisepotato** [comment]
This would also provide a general fix for #251

**Comment by wisepotato** [comment]
A new controller would like `ArticlesController`, so no more `JsonApiContext`. 

@milosloub What are your thoughts on this? I would say it makes for a more clean and conscise controller with the resources that it needs, and nothing more, allowing for better testability

```c#
        public ArticlesController(
            IJsonApiOptions jsonApiOptions,
            IResourceGraph resourceGraph,
            IResourceService<Article> resourceService) 
            : base(jsonApiOptions, resourceGraph, resourceService)
        { }
```

**Comment by milosloub** [comment]
@wisepotato I have to look more into this. This is really big stuff, I have to spend more time to this. Thanks

**Comment by wisepotato** [comment]
Discussed backward compatibility with @maurei , this will be an afterthought, after fully making what I want I'll try it in one of our V3 projects and see what breaks, and accomodate for that. I'm guessing that's something you would like to see @milosloub  💃

**Comment by wisepotato** [comment]
Being done in #588

**Comment by wisepotato** [comment]
forgot to close.

**Pull request closed without merging**
